export const venues = [
	{
		"id": 1,
		"photos": [
			"https://image.cnbcfm.com/api/v1/image/106033668-1563864541401sandbox.jpeg?v=1563864607&w=740&h=416",
			"https://image.cnbcfm.com/api/v1/image/106033677-1563864964164concept1.png?v=1563865076&w=740&h=416"
		],
		"name": "Sandbox VR",
		"description": "Go on thrilling adventures, transform into heroic characters. With your friends. See and interact inside VR just like it's real life. Great for Teams. See your friends in VR. Full-Body VR. The Star Trek Holodeck. Real-time Motion Capture. The Matrix. Hollywood Equipment.",
		"teaserDescription": "Immersive VR Team Experience",
		"hours": {
			"Sunday": { "start": 10, "end": 22 },
			"Monday": { "start": 10, "end": 22 },
			"Tuesday": { "start": 10, "end": 22 },
			"Wednesday": { "start": 10, "end": 22 },
			"Thursday": { "start": 10, "end": 22 },
			"Friday": { "start": 10, "end": 22 },
			"Saturday": { "start": 10, "end": 22 }
		},
		"phoneNumber": "(415) 625-0995",
		"email": "",
		"vibe": ["fun", "exciting"],
		"address": "767 Market St, San Francisco, CA 94103",
		"parkingAvailable": false,
		"linkToSite": "https://sandboxvr.com/sanfrancisco/",
		"tags": ["indoor", "athletic", "game"],
		"rating": 4.7,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 6],
		"price": 48,
		"priceReasoning": "Sandbox VR's experience costs $48 per person",
		"location": {
			"latitude": 37.786426,
			"longitude": -122.404609
		},
		"symbol": "sandbox-vr-sf"
	},
	{
		"id": 2,
		"photos": [
			"https://static.urbandaddy.com/uploads/assets/image/articles/standard/47a78b7f97119391669f6fbb268b46317352f69c.jpg",
			"https://infatuation.imgix.net/media/images/reviews/local-edition/banners/1525311442.75.jpg?auto=format&h=840&w=1336"
		],
		"name": "Local Edition",
		"description": "An extensive cocktail menu is offered at this underground lounge with a vintage newspaper theme.",
		"teaserDescription": "drink",
		"hours": {
			"Sunday": { "start": 0, "end": 0 },
			"Monday": { "start": 17, "end": 26 },
			"Tuesday": { "start": 17, "end": 26 },
			"Wednesday": { "start": 17, "end": 26 },
			"Thursday": { "start": 17, "end": 26 },
			"Friday": { "start": 16.5, "end": 26 },
			"Saturday": { "start": 19, "end": 26 }
		},
		"phoneNumber": "(415) 795-1375",
		"email": "",
		"vibe": ["chill"],
		"address": "691 Market St, San Francisco, CA 94105",
		"parkingAvailable": false,
		"linkToSite": "https://www.localeditionsf.com/",
		"tags": ["indoor"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 14],
		"price": 20,
		"priceReasoning": "Each glass of cocktail costs $15 or less - you may have 2 glasses",
		"location": {
			"latitude": 37.787777,
			"longitude": -122.403161
		},
		"symbol": "local-edition"
	},
	{
		"id": 3,
		"photos": [
			"https://www.blueandgoldfleet.com/wp-content/uploads/2015/04/home_Carousel_BayCruise.jpg"
		],
		"name": "Blue and Gold Fleet",
		"description": "Ferry and Boat tour operator in San Francisco, California",
		"teaserDescription": "ferry to island",
		"hours": {
			"Sunday": { "start": 9, "end": 18.45 },
			"Monday": { "start": 9, "end": 18.45 },
			"Tuesday": { "start": 9, "end": 18.45 },
			"Wednesday": { "start": 9, "end": 18.45 },
			"Thursday": { "start": 9, "end": 18.45 },
			"Friday": { "start": 9, "end": 18.45 },
			"Saturday": { "start": 9, "end": 18.45 }
		},
		"phoneNumber": "(415) 705-8200",
		"email": "",
		"vibe": ["chill", "fun", "adventurous"],
		"address": "Pier 41, San Francisco, CA 94133",
		"parkingAvailable": false,
		"linkToSite": "http://www.blueandgoldfleet.com/",
		"tags": ["outdoor", "water", "boat"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 35,
		"recommendedGroupsize": [0, 100],
		"price": 40,
		"priceReasoning": "Experiences cost vary, but their core cruise experience costs about $35 - $42",
		"location": {
			"latitude": 37.809205,
			"longitude": -122.411324
		},
		"symbol": "awesome-ferry"
	},
	{
		"id": 4	,
		"photos": [
			"https://pandorakaraoke.com/wp-content/uploads/2019/04/home-2.jpg"
		],
		"name": "Pandora Karaoke",
		"description": "Guests belt out songs in the main lounge or in themed private rooms at this bar with bottle service.",
		"teaserDescription": "drinking",
		"hours": {
			"Sunday": { "start": 18, "end": 26 },
			"Monday": { "start": 18, "end": 26 },
			"Tuesday": { "start": 18, "end": 26 },
			"Wednesday": { "start": 18, "end": 26 },
			"Thursday": { "start": 18, "end": 26 },
			"Friday": { "start": 18, "end": 26 },
			"Saturday": { "start": 18, "end": 26 }
		},
		"phoneNumber": "(415) 817-1580",
		"email": "",
		"vibe": ["chill", "fun", "club"],
		"address": "50 Mason St, San Francisco, CA 94102",
		"parkingAvailable": false,
		"linkToSite": "http://www.pandorakaraoke.com/",
		"tags": ["indoor", "sing", "dance"],
		"rating": 4.1,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 60,
		"priceReasoning": "Assuming you spend 2 hours there and have a shot of alcohol each, you may spend more/less depends on alcohol consumption",
		"location": {
			"latitude": 37.784889,
			"longitude": -122.408961
		},
		"symbol": "pandora-karaoke"
	},
	{
		"id": 5	,
		"photos": [
			"http://coinopsf.com/wp-content/uploads/2017/11/image-home-scroll-6@2x.jpg",
			"http://coinopsf.com/wp-content/uploads/2018/05/KJB0159.jpg"
		],
		"name": "The Grid",
		"description": "Coin-operated arcade games with a bar.",
		"teaserDescription": "drinking",
		"hours": {
			"Sunday": { "start": 14, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 18, "end": 26 },
			"Saturday": { "start": 18, "end": 26 }
		},
		"phoneNumber": "628-444-3277",
		"email": "info@coinopsf.com",
		"vibe": ["chill", "fun", "club"],
		"address": "508 4th St Ste. 1, San Francisco, CA 94107",
		"parkingAvailable": false,
		"linkToSite": "coinopsf.com",
		"tags": ["indoor", "sing", "dance"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 30,
		"priceReasoning": "Average price of beverage is $15",
		"location": {
			"latitude": 37.779493,
			"longitude": -122.398096
		},
		"symbol": "the-grid"
	},
	{
		"id": 6	,
		"photos": [
			"https://wearespin.com/wp-content/uploads/2018/08/SPIN_San_Francisco_Gray_Table_Website.jpg",
			"https://wearespin.com/wp-content/uploads/2020/03/T1_8783.jpg"
		],
		"name": "Spin",
		"description": "Expansive Ping-Pong place serving upscale American comfort food & drinks in a bright setting.",
		"teaserDescription": "drinking",
		"hours": {
			"Sunday": { "start": 12, "end": 20 },
			"Monday": { "start": 12, "end": 23 },
			"Tuesday": { "start": 12, "end": 23 },
			"Wednesday": { "start": 12, "end": 23 },
			"Thursday": { "start": 12, "end": 24 },
			"Friday": { "start": 12, "end": 26 },
			"Saturday": { "start": 12, "end": 26 }
		},
		"phoneNumber": "(415) 636-5995",
		"email": "wearespin.com",
		"vibe": ["chill", "fun"],
		"address": "690 Folsom St #100, San Francisco, CA 94107",
		"parkingAvailable": false,
		"linkToSite": "coinopsf.com",
		"tags": ["indoor", "athletic", "dance"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": "$$",
		"location": {
			"latitude": 37.785049,
			"longitude": -122.399168
		},
		"symbol": "spin"
	},
	{
		"id": 7	,
		"photos": [
			"https://www.inside-guide-to-san-francisco-tourism.com/image-files/ocean-beach-san-francisco-northern-end.jpg",
		],
		"name": "Ocean Beach",
		"description": "Ocean Beach is a beach on the west coast of San Francisco, California, United States, bordering the Pacific Ocean. It is adjacent to Golden Gate Park, the Richmond District, and the Sunset District.",
		"teaserDescription": "bon-fire",
		"hours": {
			"Sunday": { "start": 6, "end": 18 },
			"Monday": { "start": 6, "end": 18 },
			"Tuesday": { "start": 6, "end": 18 },
			"Wednesday": { "start": 6, "end": 18 },
			"Thursday": { "start": 6, "end": 18 },
			"Friday": { "start": 6, "end": 18 },
			"Saturday": { "start": 6, "end": 18 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "Point Lobos Ave, Great Hwy San Francisco, CA 94121",
		"parkingAvailable": true,
		"linkToSite": "",
		"tags": ["outdoor", "active", "fire"],
		"rating": 4.6,
		"takesReservations": false,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": "$$",
		"location": {
			"latitude": 37.777037,
			"longitude": -122.511938
		},
		"symbol": "ocean-beach"
	},
	{
		"id": 8,
		"photos": [
			"https://i.pinimg.com/originals/7b/5a/58/7b5a581f1a2853a2ca5aa533acf4dd81.jpg",
		],
		"name": "Urban Putt",
		"description": "Ocean Beach is a beach on the west coast of San Francisco, California, United States, bordering the Pacific Ocean. It is adjacent to Golden Gate Park, the Richmond District, and the Sunset District.",
		"teaserDescription": "mini-golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "(415) 341-1080",
		"email": "info@urbanputt.com",
		"vibe": ["fun", "active", "athletic"],
		"address": "1096 South Van Ness Avenue, San Francisco, CA 94110",
		"parkingAvailable": false,
		"linkToSite": "https://www.urbanputt.com/location/san-francisco/",
		"tags": ["indoor", "athletic", "active"],
		"rating": 4.6,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [3, 25],
		"price": 25,
		"priceReasoning": 'Mini-golf costs about $12 per adult. Average price for beverage is $12 or less',
		"location": {
			"latitude": 37.7557255,
			"longitude": -122.4190383
		},
		"symbol": "urban-putt"
	},
	{
		"id": 9,
		"photos": [
			"",
		],
		"name": "Muir Beach",
		"description": "Beach located 16.5 miles northwest of San Francisco",
		"teaserDescription": "Isolated Coastal Beach",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["beach", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "muir-beach"
	},
	{
		"id": 10,
		"photos": [
			"",
		],
		"name": "Kirby Cove",
		"description": "Beach front looking towards Golden Gate bridge.",
		"teaserDescription": "Beach front looking towards Golden Gate bridge.",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["beach", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "kirby-cove"
	},
	{
		"id": 11,
		"photos": [
			"",
		],
		"name": "Bad Axe",
		"description": "Learn to throw axes with friends.",
		"teaserDescription": "Axe Throwing",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["adventure"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "athletic"],
		"rating": 4.8,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "bad-axe"
	},
	{
		"id": 12,
		"photos": [
			"",
		],
		"name": "Pinos Palette",
		"description": "Attendees paint during evening classes at this art studio chain serving alcohol at most locations.",
		"teaserDescription": "Wine and Paint",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "paint", "drink"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "pinos-palette"
	},
	{
		"id": 13,
		"photos": [
			"",
		],
		"name": "Paint Nite",
		"description": "Attendees paint during evening classes at this art studio chain serving alcohol at most locations.",
		"teaserDescription": "Wine and Paint",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "paint", "drink"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "paint-nite"
	},
	{
		"id": 14,
		"photos": [
			"",
		],
		"name": "Palace Games",
		"description": "Historic escape rooms in San Francisco's Palace of Fine Arts. The Great Houdini, Roosevelt, and Edison Escape Rooms are great for team building or just fun!",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "adventurous"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "game"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person for a game',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "palace-games"
	},
	{
		"id": 15,
		"photos": [
			"",
		],
		"name": "Real Escape Game",
		"description": "A unique and interactive live puzzle event where teams solve mysteries and clues within a time limit.",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "adventurous"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "game"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person for a game',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "real-escape-game"
	},
	{
		"id": 16,
		"photos": [
			"",
		],
		"name": "Real Escape Game",
		"description": "A unique and interactive live puzzle event where teams solve mysteries and clues within a time limit.",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "adventurous"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "game"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person for a game',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "real-escape-game"
	},
	{
		"id": 17,
		"photos": [
			"",
		],
		"name": "Stagecoach Greens",
		"description": "Outdoor mini golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Mini Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["outdoor", "mini-golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person per game.',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "stagecoach-greens"
	},
	{
		"id": 18,
		"photos": [
			"",
		],
		"name": "Presidio Golf Course",
		"description": "Outdoor golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["outdoor", "golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person per game.',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "presidio-golf-course"
	},
	{
		"id": 19,
		"photos": [
			"",
		],
		"name": "Sub Par Miniture Golf",
		"description": "Indoor golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price per person per game.',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "sub-par-greens"
	},
	{
		"id": 20,
		"photos": [
			"",
		],
		"name": "Grand Hot Pot Lounge",
		"description": "Large, trendy eatery offering unlimited fixed-price hot pot, plus some à la carte Chinese entrees.",
		"teaserDescription": "Hot Pot",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "food", "drink"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price for 1 entree and 1 drink.',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "grand-hot-pot"
	},
	{
		"id": 21,
		"photos": [
			"",
		],
		"name": "Coin Op",
		"description": "New American bites, cocktails & craft beer in a spacious barcade with arcade classics & other games.",
		"teaserDescription": "Arcade Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "food", "drink", "game"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based upon price for 1 drink and 5 games.',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": "grand-hot-pot"
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
	{
		"id": 8,
		"photos": [
			"",
		],
		"name": "",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 0,
			"longitude": 0
		},
		"symbol": ""
	},
]
