export const venues = [
	{
		"id": 1,
		"photos": [
			"https://image.cnbcfm.com/api/v1/image/106033668-1563864541401sandbox.jpeg?v=1563864607&w=740&h=416",
			"https://image.cnbcfm.com/api/v1/image/106033677-1563864964164concept1.png?v=1563865076&w=740&h=416"
		],
		"name": "Sandbox VR",
		"description": "Go on thrilling adventures, transform into heroic characters. With your friends. See and interact inside VR just like it's real life. Great for Teams. See your friends in VR. Full-Body VR. The Star Trek Holodeck. Real-time Motion Capture. The Matrix. Hollywood Equipment.",
		"teaserDescription": "Immersive VR Team Experience",
		"hours": {
			"Sunday": { "start": 10, "end": 22 },
			"Monday": { "start": 10, "end": 22 },
			"Tuesday": { "start": 10, "end": 22 },
			"Wednesday": { "start": 10, "end": 22 },
			"Thursday": { "start": 10, "end": 22 },
			"Friday": { "start": 10, "end": 22 },
			"Saturday": { "start": 10, "end": 22 }
		},
		"phoneNumber": "(415) 625-0995",
		"email": "",
		"vibe": ["fun", "exciting"],
		"address": "767 Market St, San Francisco, CA 94103",
		"parkingAvailable": false,
		"linkToSite": "https://sandboxvr.com/sanfrancisco/",
		"tags": ["indoor", "athletic", "game"],
		"rating": 4.7,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 6],
		"price": 48,
		"priceReasoning": "Sandbox VR's experience costs $48 per person",
		"location": {
			"latitude": 37.786426,
			"longitude": -122.404609
		},
		"symbol": "sandbox-vr-sf"
	},
	{
		"id": 2,
		"photos": [
			"https://static.urbandaddy.com/uploads/assets/image/articles/standard/47a78b7f97119391669f6fbb268b46317352f69c.jpg",
			"https://infatuation.imgix.net/media/images/reviews/local-edition/banners/1525311442.75.jpg?auto=format&h=840&w=1336"
		],
		"name": "Local Edition",
		"description": "An extensive cocktail menu is offered at this underground lounge with a vintage newspaper theme.",
		"teaserDescription": "Old Age-styled Bar",
		"hours": {
			"Sunday": { "start": 0, "end": 0 },
			"Monday": { "start": 17, "end": 2 },
			"Tuesday": { "start": 17, "end": 2 },
			"Wednesday": { "start": 17, "end": 2 },
			"Thursday": { "start": 17, "end": 2 },
			"Friday": { "start": 16.5, "end": 2 },
			"Saturday": { "start": 19, "end": 2 }
		},
		"phoneNumber": "(415) 795-1375",
		"email": "",
		"vibe": ["chill"],
		"address": "691 Market St, San Francisco, CA 94105",
		"parkingAvailable": false,
		"linkToSite": "https://www.localeditionsf.com/",
		"tags": ["indoor"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 14],
		"price": 26,
		"priceReasoning": "Based on price of two individual drinks, pitchers are cheaper",
		"location": {
			"latitude": 37.787777,
			"longitude": -122.403161
		},
		"symbol": "local-edition"
	},
	{
		"id": 3,
		"photos": [
			"https://www.blueandgoldfleet.com/wp-content/uploads/2015/04/home_Carousel_BayCruise.jpg"
		],
		"name": "Blue and Gold Fleet",
		"description": "Ferry and Boat tour operator in San Francisco, California",
		"teaserDescription": "Ferry Operator",
		"hours": {
			"Sunday": { "start": 9, "end": 18.45 },
			"Monday": { "start": 9, "end": 18.45 },
			"Tuesday": { "start": 9, "end": 18.45 },
			"Wednesday": { "start": 9, "end": 18.45 },
			"Thursday": { "start": 9, "end": 18.45 },
			"Friday": { "start": 9, "end": 18.45 },
			"Saturday": { "start": 9, "end": 18.45 }
		},
		"phoneNumber": "(415) 705-8200",
		"email": "",
		"vibe": ["chill", "fun", "adventurous"],
		"address": "Pier 41, San Francisco, CA 94133",
		"parkingAvailable": false,
		"linkToSite": "http://www.blueandgoldfleet.com/",
		"tags": ["outdoor", "water", "boat"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 35,
		"recommendedGroupsize": [0, 100],
		"price": 40,
		"priceReasoning": "Based on core cruise experience round trip",
		"location": {
			"latitude": 37.809205,
			"longitude": -122.411324
		},
		"symbol": "awesome-ferry"
	},
	{
		"id": 4	,
		"photos": [
			"https://pandorakaraoke.com/wp-content/uploads/2019/04/home-2.jpg"
		],
		"name": "Pandora Karaoke",
		"description": "Guests belt out songs in the main lounge or in themed private rooms at this bar with bottle service.",
		"teaserDescription": "Karaoke Bar",
		"hours": {
			"Sunday": { "start": 18, "end": 26 },
			"Monday": { "start": 18, "end": 26 },
			"Tuesday": { "start": 18, "end": 26 },
			"Wednesday": { "start": 18, "end": 26 },
			"Thursday": { "start": 18, "end": 26 },
			"Friday": { "start": 18, "end": 26 },
			"Saturday": { "start": 18, "end": 26 }
		},
		"phoneNumber": "(415) 817-1580",
		"email": "",
		"vibe": ["chill", "fun", "club"],
		"address": "50 Mason St, San Francisco, CA 94102",
		"parkingAvailable": false,
		"linkToSite": "http://www.pandorakaraoke.com/",
		"tags": ["indoor", "sing", "dance"],
		"rating": 4.1,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 50,
		"priceReasoning": "Based on cost of two drinks and two hours in private room",
		"location": {
			"latitude": 37.784889,
			"longitude": -122.408961
		},
		"symbol": "pandora-karaoke"
	},
	{
		"id": 5	,
		"photos": [
			"http://coinopsf.com/wp-content/uploads/2017/11/image-home-scroll-6@2x.jpg",
			"http://coinopsf.com/wp-content/uploads/2018/05/KJB0159.jpg"
		],
		"name": "The Grid",
		"description": "Coin-operated arcade games with a bar.",
		"teaserDescription": "Coin-op Bar",
		"hours": {
			"Sunday": { "start": 14, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 18, "end": 26 },
			"Saturday": { "start": 18, "end": 26 }
		},
		"phoneNumber": "628-444-3277",
		"email": "info@coinopsf.com",
		"vibe": ["chill", "fun", "club"],
		"address": "508 4th St Ste. 1, San Francisco, CA 94107",
		"parkingAvailable": false,
		"linkToSite": "coinopsf.com",
		"tags": ["indoor", "sing", "dance"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 30,
		"priceReasoning": "Based on price for two drinks",
		"location": {
			"latitude": 37.779493,
			"longitude": -122.398096
		},
		"symbol": "the-grid"
	},
	{
		"id": 6	,
		"photos": [
			"https://wearespin.com/wp-content/uploads/2018/08/SPIN_San_Francisco_Gray_Table_Website.jpg",
			"https://wearespin.com/wp-content/uploads/2020/03/T1_8783.jpg"
		],
		"name": "Spin",
		"description": "Expansive Ping-Pong place serving upscale American comfort food & drinks in a bright setting.",
		"teaserDescription": "Ping-Pong Bar",
		"hours": {
			"Sunday": { "start": 12, "end": 20 },
			"Monday": { "start": 12, "end": 23 },
			"Tuesday": { "start": 12, "end": 23 },
			"Wednesday": { "start": 12, "end": 23 },
			"Thursday": { "start": 12, "end": 24 },
			"Friday": { "start": 12, "end": 26 },
			"Saturday": { "start": 12, "end": 26 }
		},
		"phoneNumber": "(415) 636-5995",
		"email": "wearespin.com",
		"vibe": ["chill", "fun"],
		"address": "690 Folsom St #100, San Francisco, CA 94107",
		"parkingAvailable": false,
		"linkToSite": "coinopsf.com",
		"tags": ["indoor", "athletic", "dance"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 40,
		"priceReasoning": "Based on price for two drinks and 1 hour table reservation",
		"location": {
			"latitude": 37.785049,
			"longitude": -122.399168
		},
		"symbol": "spin"
	},
	{
		"id": 7	,
		"photos": [
			"https://www.inside-guide-to-san-francisco-tourism.com/image-files/ocean-beach-san-francisco-northern-end.jpg",
		],
		"name": "Ocean Beach",
		"description": "Ocean Beach is a beach on the west coast of San Francisco, California, United States, bordering the Pacific Ocean. It is adjacent to Golden Gate Park, the Richmond District, and the Sunset District.",
		"teaserDescription": "Beach",
		"hours": {
			"Sunday": { "start": 6, "end": 18 },
			"Monday": { "start": 6, "end": 18 },
			"Tuesday": { "start": 6, "end": 18 },
			"Wednesday": { "start": 6, "end": 18 },
			"Thursday": { "start": 6, "end": 18 },
			"Friday": { "start": 6, "end": 18 },
			"Saturday": { "start": 6, "end": 18 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "Point Lobos Ave, Great Hwy San Francisco, CA 94121",
		"parkingAvailable": true,
		"linkToSite": "",
		"tags": ["outdoor", "active", "fire"],
		"rating": 4.6,
		"takesReservations": false,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [4, 25],
		"price": 0,
		"priceReasoning": "",
		"location": {
			"latitude": 37.777037,
			"longitude": -122.511938
		},
		"symbol": "ocean-beach"
	},
	{
		"id": 8,
		"photos": [
			"https://i.pinimg.com/originals/7b/5a/58/7b5a581f1a2853a2ca5aa533acf4dd81.jpg",
		],
		"name": "Urban Putt",
		"description": "Unique restaurant featuring American grub & drinks in an informal space housing a mini-golf course.",
		"teaserDescription": "Mini-golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "(415) 341-1080",
		"email": "info@urbanputt.com",
		"vibe": ["fun", "active", "athletic"],
		"address": "1096 South Van Ness Avenue, San Francisco, CA 94110",
		"parkingAvailable": false,
		"linkToSite": "https://www.urbanputt.com/location/san-francisco/",
		"tags": ["indoor", "athletic", "active"],
		"rating": 4.6,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [3, 25],
		"price": 12,
		"priceReasoning": 'Based on price per game',
		"location": {
			"latitude": 37.7557255,
			"longitude": -122.4190383
		},
		"symbol": "urban-putt"
	},
	{
		"id": 9,
		"photos": [
			"https://www.nps.gov/goga/planyourvisit/images/MUBE_141122_KW_033.jpg?maxwidth=1200&maxheight=1200&autorotate=false",
			"https://www.parksconservancy.org/sites/default/files/styles/basic/public/resource-gallery/A_MUBE_100727_MCu_1.jpg?itok=MaxtPUMX"
		],
		"name": "Muir Beach",
		"description": "Beach located 16.5 miles northwest of San Francisco",
		"teaserDescription": "Isolated Coastal Beach",
		"hours": {
			"Sunday": { "start": 6, "end": 18 },
			"Monday": { "start": 6, "end": 18 },
			"Tuesday": { "start": 6, "end": 18 },
			"Wednesday": { "start": 6, "end": 18 },
			"Thursday": { "start": 6, "end": 18 },
			"Friday": { "start": 6, "end": 18 },
			"Saturday": { "start": 6, "end": 18 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "Muir Beach, CA",
		"parkingAvailable": true,
		"linkToSite": "",
		"tags": ["beach", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.8664252,
			"longitude": -122.6036196
		},
		"symbol": "muir-beach"
	},
	{
		"id": 10,
		"photos": [
			"",
		],
		"name": "Kirby Cove",
		"description": "Beach front looking towards Golden Gate bridge.",
		"teaserDescription": "Beach front looking towards Golden Gate bridge.",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "Kirby Cove Road, CA 94941",
		"parkingAvailable": true,
		"linkToSite": "",
		"tags": ["beach", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 60,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.8260793,
			"longitude": -122.5073465
		},
		"symbol": "kirby-cove"
	},
	{
		"id": 11,
		"photos": [
			"https://s3-media0.fl.yelpcdn.com/bphoto/8_VRoCXV-dUPEhCgnXRWVg/o.jpg",
			"https://s3-media0.fl.yelpcdn.com/bphoto/FPsfaVnr2bB4_izn1WHTpQ/o.jpg"
		],
		"name": "Bad Axe",
		"description": "Learn to throw axes with friends.",
		"teaserDescription": "Axe Throwing",
		"hours": {
			"Sunday": { "start": 8, "end": 23 },
			"Monday": { "start": 8, "end": 23 },
			"Tuesday": { "start": 8, "end": 23 },
			"Wednesday": { "start": 8, "end": 23 },
			"Thursday": { "start": 8, "end": 23 },
			"Friday": { "start": 8, "end": 23 },
			"Saturday": { "start": 8, "end": 23 }
		},
		"phoneNumber": "(844) 818-0999",
		"email": "",
		"vibe": ["adventure"],
		"address": "30 Hill St, Daly City, CA 94014",
		"parkingAvailable": false,
		"linkToSite": "https://badaxethrowing.com/locations/axe-throwing-san-francisco/",
		"tags": ["indoor", "athletic"],
		"rating": 4.8,
		"takesReservations": true,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [4, 30],
		"price": 40,
		"priceReasoning": 'Based on 2 hours of group event with coaches',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "bad-axe"
	},
	{
		"id": 12,
		"photos": [
			"https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_789,q_75,w_954/https://assets.simpleviewinc.com/simpleview/image/upload/crm/palmsprings/PinotsPaletteNightOut0-bc42e82c5056b36_bc42eca2-5056-b365-ab389af923e8fc16.jpg",
			"https://assets.simpleviewinc.com/simpleview/image/fetch/c_limit,q_75,w_1200/https://assets.simpleviewinc.com/simpleview/image/upload/crm/palmsprings/PinotsPalette0_2d086e5b-5056-b365-abcb06088b3ef64c.jpg"
		],
		"name": "Pinos Palette",
		"description": "Attendees paint during evening classes at this art studio chain serving alcohol at most locations.",
		"teaserDescription": "Wine and Paint",
		"hours": {
			"Sunday": { "start": 9, "end": 22 },
			"Monday": { "start": 9, "end": 22 },
			"Tuesday": { "start": 9, "end": 22 },
			"Wednesday": { "start": 9, "end": 22 },
			"Thursday": { "start": 9, "end": 22 },
			"Friday": { "start": 9, "end": 22 },
			"Saturday": { "start": 9, "end": 22 }
		},
		"phoneNumber": "(415) 525-4722",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "1981 Sutter St, San Francisco, CA 94115",
		"parkingAvailable": false,
		"linkToSite": "https://www.pinotspalette.com/fillmoredistrict/party-request?reference=corporateevents_cta",
		"tags": ["indoor", "paint", "drink"],
		"rating": 4.3,
		"takesReservations": true,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [10, 50],
		"price": 39,
		"priceReasoning": 'Based on price per class',
		"location": {
			"latitude": 37.7860192,
			"longitude": -122.4350784
		},
		"symbol": "pinos-palette"
	},
	{
		"id": 13,
		"photos": [
			"https://d28m5bx785ox17.cloudfront.net/v1/img/t-EeHE4TzQxEPv7Dkk0M_XWtviZMl2bGnUmcNQQoOpI=",
			"https://d28m5bx785ox17.cloudfront.net/v1/img/Yl6LrFOZRO-Ut0pH8-nmsN6AdOkg_uqb1_ZnEqC_Ygc="
		],
		"name": "Paint Nite",
		"description": "Attendees paint during evening classes at this art studio chain serving alcohol at most locations.",
		"teaserDescription": "Wine and Paint",
		"hours": {
			"Sunday": { "start": 9, "end": 22 },
			"Monday": { "start": 9, "end": 22 },
			"Tuesday": { "start": 9, "end": 22 },
			"Wednesday": { "start": 9, "end": 22 },
			"Thursday": { "start": 9, "end": 22 },
			"Friday": { "start": 9, "end": 22 },
			"Saturday": { "start": 9, "end": 22 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill", "fun"],
		"address": "1881 Post St, San Francisco, CA 94115",
		"parkingAvailable": false,
		"linkToSite": "https://www.yaymaker.com/private-events/corporate-events/#planning-form",
		"tags": ["indoor", "paint", "drink"],
		"rating": 4.5,
		"takesReservations": true,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [10, 50],
		"price": 27,
		"priceReasoning": 'Based on price per class',
		"location": {
			"latitude": 37.7855034,
			"longitude": -122.4349522
		},
		"symbol": "paint-nite"
	},
	{
		"id": 14,
		"photos": [
			"https://3jsnt91p9m6y2ownxz2ljlp7-wpengine.netdna-ssl.com/wp-content/uploads/2018/09/escape-room-tips-and-tricks.png",
			"https://palace-games.com/wp-content/uploads/2019/06/Palace_of_Fine_Arts_SF_CA.jpg"
		],
		"name": "Palace Games",
		"description": "Historic escape rooms in San Francisco's Palace of Fine Arts. The Great Houdini, Roosevelt, and Edison Escape Rooms are great for team building or just fun!",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 9, "end": 22 },
			"Monday": { "start": 10, "end": 22 },
			"Tuesday": { "start": 10, "end": 22 },
			"Wednesday": { "start": 10, "end": 22 },
			"Thursday": { "start": 10, "end": 22 },
			"Friday": { "start": 10, "end": 23 },
			"Saturday": { "start": 9, "end": 23 }
		},
		"phoneNumber": "(415) 997-8522",
		"email": "",
		"vibe": ["fun", "adventurous"],
		"address": "3362 Palace Dr, San Francisco, CA 94123",
		"parkingAvailable": false,
		"linkToSite": "https://palace-games.com/team-building/",
		"tags": ["indoor", "game"],
		"rating": 4.8,
		"takesReservations": true,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [4, 15],
		"price": 50,
		"priceReasoning": 'Based upon price per room',
		"location": {
			"latitude": 37.8032781,
			"longitude": -122.4516369
		},
		"symbol": "palace-games"
	},
	{
		"id": 15,
		"photos": [
			"https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/42570319_2488633197833847_1228141908266582016_o.jpg?_nc_cat=108&_nc_sid=6e5ad9&_nc_ohc=iqh5uT7tILkAX_IXuc8&_nc_ht=scontent-sjc3-1.xx&oh=14249221908c69881c49876d177d118b&oe=5E955E5A",
			"https://s3-media0.fl.yelpcdn.com/bphoto/WWajKRKfPMP5v7CuPNoCiQ/o.jpg"
		],
		"name": "Real Escape Game",
		"description": "A unique and interactive live puzzle event where teams solve mysteries and clues within a time limit.",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 12, "end": 17 },
			"Monday": { "start": null, "end": null },
			"Tuesday": { "start": 14, "end": 21 },
			"Wednesday": { "start": 14, "end": 21 },
			"Thursday": { "start": 14, "end": 21 },
			"Friday": { "start": 14, "end": 21 },
			"Saturday": { "start": 12, "end": 21 }
		},
		"phoneNumber": "(415) 800-2004",
		"email": "",
		"vibe": ["fun", "adventurous"],
		"address": "1746 Post St, San Francisco, CA 94115",
		"parkingAvailable": false,
		"linkToSite": "https://realescapegame.com/sfrooms/",
		"tags": ["indoor", "game"],
		"rating": 4.6,
		"takesReservations": true,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [4, 20],
		"price": 16,
		"priceReasoning": 'Based upon price per game',
		"location": {
			"latitude": 37.785756,
			"longitude": -122.4327911
		},
		"symbol": "real-escape-game"
	},
	{
		"id": 17,
		"photos": [
			"",
		],
		"name": "Stagecoach Greens",
		"description": "Outdoor mini golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Mini Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["outdoor", "mini-golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 16,
		"priceReasoning": 'Based upon price per game.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "stagecoach-greens"
	},
	{
		"id": 18,
		"photos": [
			"",
		],
		"name": "Presidio Golf Course",
		"description": "Outdoor golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["outdoor", "golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 130,
		"priceReasoning": 'Based upon price per person per game with all amenities.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "presidio-golf-course"
	},
	{
		"id": 19,
		"photos": [
			"",
		],
		"name": "Sub Par Miniture Golf",
		"description": "Indoor golf course and experience the history, invention and fun of San Francisco.",
		"teaserDescription": "Golf",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "golf"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 12,
		"priceReasoning": 'Based upon price per person per game.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "sub-par-greens"
	},
	{
		"id": 20,
		"photos": [
			"",
		],
		"name": "Grand Hot Pot Lounge",
		"description": "Large, trendy eatery offering unlimited fixed-price hot pot, plus some à la carte Chinese entrees.",
		"teaserDescription": "Hot Pot",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "food", "drink"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 28,
		"priceReasoning": 'Based upon price for all you can eat and drink',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "grand-hot-pot"
	},
	{
		"id": 21,
		"photos": [
			"",
		],
		"name": "Coin Op",
		"description": "New American bites, cocktails & craft beer in a spacious barcade with arcade classics & other games.",
		"teaserDescription": "Arcade Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "food", "drink", "game"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 20,
		"priceReasoning": 'Based upon price for 1 drink and 5 games.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "coin-op"
	},
	{
		"id": 22,
		"photos": [
			"",
		],
		"name": "Emporium",
		"description": "Pinball, pool & old-school arcade games, plus music, cocktails & craft beers, in hip, historic digs.",
		"teaserDescription": "Arcade Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "silly"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["game", "bar", "drink", "indoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 20,
		"priceReasoning": 'Based upon price for 1 drink and 5 games..',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "emporium"
	},
	{
		"id": 23,
		"photos": [
			"",
		],
		"name": "Reason",
		"description": "SF's highest technology escape room with a flair for the future.",
		"teaserDescription": "Escape Room",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["tech", "adventure"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "escape"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 50,
		"priceReasoning": 'Based upon price for 1 games.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "reason"
	},
	{
		"id": 24,
		"photos": [
			"",
		],
		"name": "Everdene",
		"description": "The lively, 12th-story cocktail den at Virgin Hotels SF has big views, live DJs & New American eats.",
		"teaserDescription": "Rooftop Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["high-end"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["bar", "indoor", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on cost of 2 drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "everdenes"
	},
	{
		"id": 25,
		"photos": [
			"",
		],
		"name": "Clay By The Bay",
		"description": "Pottery Class",
		"teaserDescription": "Pottery Class",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "creative"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "class", "messy"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 69,
		"priceReasoning": 'Based on price per class',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "clay-bays"
	},
	{
		"id": 26,
		"photos": [
			"",
		],
		"name": "Jordan's Kitchen",
		"description": "The premier place in San Francisco for hands on cooking classes.",
		"teaserDescription": "Cooking Class",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["food", "cooking", "indoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 60,
		"priceReasoning": 'Based on price per class',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "jordans-kitchens"
	},
	{
		"id": 27,
		"photos": [
			"",
		],
		"name": "Fat Tire Tours",
		"description": "Segway Tour",
		"teaserDescription": "Segway Tour",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["explore"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["outdoor", "segway", "tour"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 75,
		"priceReasoning": 'Based on price per tour per person',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "fat-tire"
	},
	{
		"id": 28,
		"photos": [
			"",
		],
		"name": "K1 Speed",
		"description": "Chain of indoor racing centers featuring electric go-karting for all skill levels, plus food.",
		"teaserDescription": "Indoor Go Karts",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["competitve", "thrill"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "go kart", "food"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 65,
		"priceReasoning": 'Based on price for 3 races',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "k1-speed"
	},
	{
		"id": 29,
		"photos": [
			"",
		],
		"name": "Dogpatch WineWorks",
		"description": "Airy, industrial-style winery with collective winemaking & classes, plus tastings on Sunday.",
		"teaserDescription": "Wine-based Classes and Tasting",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "class", "wine"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 60,
		"priceReasoning": 'Based on price per class',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "dogpatch-wine"
	},
	{
		"id": 30,
		"photos": [
			"",
		],
		"name": "San Francisco-Marin Food Bank",
		"description": "Food Bank",
		"teaserDescription": "Food Bank",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "charity"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "sf-food-bank"
	},
	{
		"id": 31,
		"photos": [
			"",
		],
		"name": "Breakthrough Sushi",
		"description": "The first and only sustainable sushi making classes company, serving San Francisco Bay Area.",
		"teaserDescription": "Sushi Classes",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "creative"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "class", "food"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 180,
		"priceReasoning": 'Based on price per class. Minimum budget is $1800.',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "break-sushi"
	},
	{
		"id": 32,
		"photos": [
			"",
		],
		"name": "Gott's Roadside",
		"description": "Retro eatery offering locally sourced burgers, fish tacos & beer, plus outdoor picnic tables.",
		"teaserDescription": "Low-key Restaurant",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["chill"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["food", "outdoor"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 25,
		"priceReasoning": 'Based on price of one drink and one entree',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "gotts"
	},
	{
		"id": 33,
		"photos": [
			"",
		],
		"name": "Dave and Buster's",
		"description": "Family-friendly chain offering a sports-bar-style setting for American food & arcade games.",
		"teaserDescription": "Arcade Bar and Grill",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["fun", "exciting"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "game", "bar", "food"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on 1 hour of play time',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": "dave-buster"
	},
	{
		"id": 34,
		"photos": [
			"",
		],
		"name": "",
		"description": "MoMA contains exhibitions and collection of modern and contemporary art",
		"teaserDescription": "High-End Art Museum",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": ["creative"],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": ["indoor", "museum", "art"],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 25,
		"priceReasoning": 'Based on price per ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 35,
		"photos": [
			"",
		],
		"name": "Oracle Park",
		"description": "Baseball park located in the South Beach",
		"teaserDescription": "Baseball Park",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 50,
		"priceReasoning": 'Based on price per weekday club-level ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 36,
		"photos": [
			"",
		],
		"name": "Exploratorium",
		"description": "The Exploratorium is a museum of science, technology, and arts in San Francisco. Its mission is to create inquiry-based experiences that transform learning worldwide.",
		"teaserDescription": "Science Museum",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on price per ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 37,
		"photos": [
			"",
		],
		"name": "Museum of Ice Cream",
		"description": "Museum of Ice Cream transforms concepts and dreams into spaces that provoke imagination and creativity.",
		"teaserDescription": "Ice Cream Museum",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on price per museum ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 38,
		"photos": [
			"",
		],
		"name": "Alcatraz Island",
		"description": "The small island was developed with facilities for a lighthouse, a military fortification, and a military prison.",
		"teaserDescription": "Prison Island turned Tour",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 40,
		"priceReasoning": 'Based on price for ferry and tour ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 39,
		"photos": [
			"",
		],
		"name": "Golden Gate Fortune Cookie Factory",
		"description": "Landmark bakery prepares homemade fortune cookies in a tiny open kitchen, with free tours available.",
		"teaserDescription": "Fortune Cookie Tours and Store",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": 'Based on price for tour',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 40,
		"photos": [
			"",
		],
		"name": "Aquarium of the Bay",
		"description": "Aquarium of the Bay is a public aquarium located at The Embarcadero.",
		"teaserDescription": "Aquarium",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 28,
		"priceReasoning": 'Based on price per museum ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 41,
		"photos": [
			"",
		],
		"name": "Mission Dolores Park",
		"description": "A city park in San Francisco, California. Known for its various social and recreational activities.",
		"teaserDescription": "Fun City Park",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 71,
		"photos": [
			"",
		],
		"name": "San Francisco Whale Tours",
		"description": "Whale watching tour agency in San Francisco, California.",
		"teaserDescription": "Whale Watching Tours",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 59,
		"priceReasoning": 'Based on price per tour ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 42,
		"photos": [
			"",
		],
		"name": "Ghiradelli Factory",
		"description": "Ghirardelli represents a range of truly exceptional chocolate and ice cream experiences.",
		"teaserDescription": "Ice cream and Chcocolate Factory",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 9,
		"priceReasoning": 'Based on price of average ice cream item',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 43,
		"photos": [
			"",
		],
		"name": "Blue and Gold Sausolito",
		"description": "Boat tour agency in San Francisco, California.",
		"teaserDescription": "Ferry Boat",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 26,
		"priceReasoning": 'Based on price for round-trip ferry ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 44,
		"photos": [
			"",
		],
		"name": "Blue and Gold Angel Island",
		"description": "Boat tour agency in San Francisco, California.",
		"teaserDescription": "Ferry Boat to Angel Island",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 20,
		"priceReasoning": 'Based on price for round-trip ferry ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 45,
		"photos": [
			"",
		],
		"name": "Angel Island State Park",
		"description": "Originally the home of a military installation, the island now offers picturesque views of the San Francisco skyline.",
		"teaserDescription": "Island",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 46,
		"photos": [
			"",
		],
		"name": "Japanese Tea Garden",
		"description": "The oldest public Japanese garden in the United States located inside Golden Gate Park in San Francisco, California.",
		"teaserDescription": "Public Garden",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 9,
		"priceReasoning": 'Based on price for individual entry',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 47,
		"photos": [
			"",
		],
		"name": "San Francisco Zoo",
		"description": "The San Francisco Zoo is a 100-acre zoo",
		"teaserDescription": "City Zoo",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 22,
		"priceReasoning": 'Based on price for individual entry',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 48,
		"photos": [
			"",
		],
		"name": "Encore Karaoke Lounge",
		"description": "Low-key karaoke lounge serving up a large selection of music plus happy hour 7 days a week.",
		"teaserDescription": "Karaoke Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on price for two drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 49,
		"photos": [
			"",
		],
		"name": "Fillmore Karaoke",
		"description": "Low-key karaoke lounge serving up a large selection of music plus happy hour 7 days a week.",
		"teaserDescription": "Karaoke Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on price for two drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 50,
		"photos": [
			"",
		],
		"name": "Dandelion Chocolate Factory",
		"description": "Dandelion Chocolate is a small-batch bean-to-bar craft chocolate maker offering classes, factory tours, cafès and retail shops from San Francisco.",
		"teaserDescription": "Chocolate Classes and Tours",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 90,
		"priceReasoning": 'Based on price for choclate class',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 51,
		"photos": [
			"",
		],
		"name": "The San Francisco Chocolate Factory",
		"description": "Small chocolate factory and store.",
		"teaserDescription": "Chocolate Factory",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 10,
		"priceReasoning": 'Based on price for gift chocolate',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 52,
		"photos": [
			"",
		],
		"name": "Gregangelo Museum",
		"description": "Circus troupe and entertainment company that incorporates the arts.",
		"teaserDescription": "Entertainment And Museum",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 70,
		"priceReasoning": 'Based on price for tour',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 53,
		"photos": [
			"",
		],
		"name": "Pacifica Archery",
		"description": "Full-service archery shop with a range of bows & accessories, plus indoor practice lanes & lessons.",
		"teaserDescription": "Archery Lessons",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 60,
		"priceReasoning": 'Based on price per event',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 54,
		"photos": [
			"",
		],
		"name": "Lucky Strike",
		"description": "Mod bowling spot offering many lanes, a lounge, dancing & regular DJs, with a 21+ policy at night.",
		"teaserDescription": "Bowling Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 50,
		"priceReasoning": 'Based on price for 1 game and 2 drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 55,
		"photos": [
			"",
		],
		"name": "Mission Bowling Club",
		"description": "Retro bowling alley with 6 lanes, a full bar & attached restaurant serving upscale comfort fare.",
		"teaserDescription": "Bowling",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 20,
		"priceReasoning": 'Based on price for 1 game',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 56,
		"photos": [
			"",
		],
		"name": "Yerba Buena Ice Skating and Bowling",
		"description": "San Francisco's premier Ice Skating and Bowling Center open daily.",
		"teaserDescription": "Ice Skating and Bowling.",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 20,
		"priceReasoning": 'Based on price for 1 bowling game',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 57,
		"photos": [
			"",
		],
		"name": "Paniq Escape Room",
		"description": "",
		"teaserDescription": "",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 34,
		"priceReasoning": 'Based on price per game',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 58,
		"photos": [
			"",
		],
		"name": "Maritime Wine Tasting Studio",
		"description": "Urban winetasting, bar, and restaurant.",
		"teaserDescription": "Winetasting",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 60,
		"priceReasoning": 'Based on price for 2 drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 59,
		"photos": [
			"",
		],
		"name": "Treasure Island",
		"description": "An artificial island in the San Francisco Bay.",
		"teaserDescription": "Island",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 0,
		"priceReasoning": '',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 60,
		"photos": [
			"",
		],
		"name": "Vie Winery and Bocce",
		"description": "Fun winery and bar accommadated with a bocce bit.",
		"teaserDescription": "Winery and Bar",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 30,
		"priceReasoning": 'Based on price for 2 drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 61,
		"photos": [
			"",
		],
		"name": "Sol Rouge Winery",
		"description": "Wine tasting room with roots in Napa Valley.",
		"teaserDescription": "Wine Tasting",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 60,
		"priceReasoning": 'Based on price for two drinks',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 63,
		"photos": [
			"",
		],
		"name": "Bar Bocce",
		"description": "Low-key fan favorite bar with pizza and drinks overlooking the bay of Sausolito.",
		"teaserDescription": "Bar with Bocce Pit",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 25,
		"priceReasoning": 'Based on price for 1 pizza and 1 drink',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
	{
		"id": 64,
		"photos": [
			"",
		],
		"name": "Angel Island–Tiburon Ferry",
		"description": "Ferry to Angel Island in San Francisco, California.",
		"teaserDescription": "Ferry Boat to Angel Island",
		"hours": {
			"Sunday": { "start": 11, "end": 24 },
			"Monday": { "start": 16, "end": 24 },
			"Tuesday": { "start": 16, "end": 24 },
			"Wednesday": { "start": 16, "end": 24 },
			"Thursday": { "start": 16, "end": 24 },
			"Friday": { "start": 16, "end": 1 },
			"Saturday": { "start": 11, "end": 1 }
		},
		"phoneNumber": "",
		"email": "",
		"vibe": [""],
		"address": "",
		"parkingAvailable": false,
		"linkToSite": "",
		"tags": [""],
		"rating": 4.5,
		"takesReservations": false,
		"averageTimeSpent": 120,
		"recommendedGroupsize": [1, 5],
		"price": 15,
		"priceReasoning": 'Based on price for round-trip ferry ticket',
		"location": {
			"latitude": 37.2288683,
			"longitude": -122.2603425
		},
		"symbol": ""
	},
]
